name: learn-github-actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci
      - name: Build production project
        run: npm run build:prod
      - name: Linting typescript
        run: npm run lint:ts
      - name: Linting scss
        run: npm run lint:scss
      - name: Unit testing
        run: npm run test:unit
      - name: Build storybook
        run: npm run build-storybook
      - name: Screenshot testing
        run: npm run test:ui:ci

